services:
  - type: web
    name: library-management
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn library_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DJANGO_SETTINGS_MODULE
        value: library_project.settings
